data_dir: gs://justhungryman_tpu5/tf_records
type: tensorflow_records
batch_size: ???
train:
  split: "train"  # 49k
  drop_remainder: True

  repeat: True
  shuffle: True
  batch_size: ???
  
  preprocess: ???
  postprocess: ???
  
